(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 500,
	height: 500,
	fps: 24,
	color: "#FFFFFF",
	webfonts: {},
	manifest: []
};



lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib.flash01 = function() {
	this.spriteSheet = ss["script_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.Persivald = function() {
	this.spriteSheet = ss["script_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.text3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFF00").s().p("Aj9FcQgJgJAAgMQAAgVASgPQAQgQAWAAQAPAAALAIQAJAJAAAOQAAAPgJAMQAEAWgPgDIgMgCQgLAGgNAAQgRAAgJgIgAiuD3QAAgGADgEIBvisIA8hiIAbgzQBRiPAzhAQAyhAAiAAQAIAAAHAGQAFAGAAAIQAAAUgRAgQAEAFAAAGQAAAJgIANQgIAMgRAUIlYGsQgOASgEAGQgFAEgEAAIgCAAIgGAKQgBAEgGAAQgFAAAAgFg");
	this.shape.setTransform(247.1,-28.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFF00").s().p("AgYCNQgOgRAAgYQAAgzAlg2IhSABIgcAqIgDAJQgEAPgMANQgDAFgIAGIgrBFQgBABgDAAIg7AAQgFAAgBgCQgBgDAFgEIBnidIgBgCQAGgKAHgJIBPh3QACgHAHAAIA0gBIACACIABAEIgeAwQAGAJAAAPQAAAOgFAQIgFAMIAxAAQAyg3AzgfQAyggAfAAQAPABALAMQAKALAAAUQAAASgKAZQgKAZgPAbQgOAZgRAcQgRAcgQAVIAHAAQASAAAXgOQAYgNAVgZIAHgHQAAAAABgBQAAAAABAAQAAAAABAAQABgBABAAQAGAAAAAGQAAAGgLALQgMAMgSALQgSALgTAKQgVAIgOAAIgIAAQgiAkgdALQgeAMgdAAQgTAAgQgRgAACCCQAAAHAFADQAFAGAGAAQAYAAAWgNQAXgNAagdQgFgHAAgKIAAgBQgtAogkAAQgNAAgHgGQgFAOAAAJgACVhdIgQALQgDAEgDADQgaAegXAgQgWAdgSAdQgQAbgLAXIgBACQAEAJAOAAQAkAAAvg0QADgJAGgJIAMgMQgGgGAAgJQAAgbAZAAQAGAAAEAFQAggwAAgZQAAgTgRAAQgMAAgPAMgADKhVQAAAngwBBIAGACQAJgMALgPQAMgTALgTQAKgVAIgVQAHgVAAgRQAAgIgFgGQgGgEgIAAQgHAAgHACQgHAEgJAHIgTARIARgBQAZAAAAAcgAhPgKIBRgBIAHgKIgvgBQgLAEgeAIgAgphGIANgVg");
	this.shape_1.setTransform(200.3,-8.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFF00").s().p("AimCcQgVAAgFgQQgDgJABgMIgBgFQgCgMAAgMQAAgQAGgSQAGgTALgOQAKgRAOgIQAMgLAQAAQASAAAIALQAJAIABANQABAMgHAMQgHALgPAAQgIAAgEgCQgEgCgJAAIgEAAQgLAMgLAOQgMATgFASIgBADIAAABQAEAQARAKIADABIAQgMIAwgqIAhgeIAcgkIApg1QAXgdAXgZQAWgbAUgUQATgTAPgHIBDgBQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABQAAAEgNARIgpA3QAEAAAEgCIgbAcIgLAPQg2BJgZApQgZApAAAQIAAADQArgcBNhYIAGAGQhPBWgtAdQADADAIAAQAKAAAUgPQASgRAWgVIArgsQAWgWAPgNQADABAAAEIAAABIgCAEIhEBKQgaAbgRANQgRAOgMADQgMAEgNAAQgJAAgHgEQgKAEgHAAQgWAAAFgfQAEgdATgeIAGgNQAMgeAdgmIgLAKIgqAnIgJAJIgYAhQgXAfgYAXIgVASQgJAHgRACQgJAAgGgCgAi5CNQABAIAIABQgGgFgEgHIABADgAghCGQgDAPAPAAIAHgBIgDgEQgJgIgCgOQgFAHAAAFgAhwB1QgQAQgKAIIAOgIQAJgHAIgJIAQgTIgVATgAA0hAQggAlgYAjIAXgXQAQgPAPgNIBIhfQgmAkggAmg");
	this.shape_2.setTransform(169.9,-9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFF00").s().p("AkAEkQgMgOAAgYQAAgNAEgRIAAgOQADgpA1hOQA8hYA8hQQAxhDA2gvIAOgNIAagYQAYgVATgIQATgIAQgCQARgDAPACQAOABAPgDQAPgBATgIQASgIAXgUQgHAwgXAdIACABQgNAfgPAMQgUANgugDIgbgPQguAAgZAEIgRALQgeAbgXAeQgZAegVAeIgoA5QgSAZgPAUQARgQASgLQATgKASgGQARgDAOgBIAZgCQAPAAAOAOQANARAAATQAAAqgYAwQgXAvgmAmQgmAngtAZQguAZgqAAQgSAAgMgQgAjiEqQAGAAAHgCQgSgBgLgKQABANAPAAgAhqA/IgGAHQgYAagXAhIgLAOQgxBJgDApQgDAcAQAAQAQAAAVgOQAigfAug/IADgDQAphGAEgrQACgVgTAAQgVAAgYAXgAgQAyQAGgPAAgLQAAgOgPgCIgCAAQgQAAgWARIgJAHIAPgBQAaABARASg");
	this.shape_3.setTransform(151.5,-23.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFF00").s().p("AgYCNQgOgRAAgYQAAgzAlg2IhSABIgcAqIgDAJQgEAPgLANQgFAFgHAGIgqBFQgCABgEAAIg5AAQgGAAgBgCQgBgDAFgEIBnidIgBgCQAHgKAGgJIBPh3QACgHAHAAIA0gBIACACIABAEIgeAwQAGAJAAAPQAAAOgFAQIgGAMIAyAAQAzg3AygfQAyggAfAAQAPABALAMQAKALAAAUQAAASgKAZQgKAZgPAbQgOAZgRAcQgSAcgPAVIAHAAQASAAAXgOQAYgNAVgZIAHgHQAAAAABgBQAAAAABAAQAAAAABAAQABgBABAAQAGAAAAAGQAAAGgMALQgLAMgSALQgSALgTAKQgVAIgOAAIgIAAQgiAkgdALQgeAMgdAAQgTAAgQgRgAACCCQAAAHAFADQAFAGAGAAQAYAAAWgNQAXgNAagdQgFgHgBgKIAAgBQgsAogkAAQgNAAgHgGQgFAOAAAJgACVhdIgQALQgCAEgEADQgaAegXAgQgWAdgSAdQgQAbgLAXIgBACQAEAJAOAAQAkAAAvg0QADgJAGgJIAMgMQgGgGAAgJQAAgbAZAAQAFAAAFAFQAggwAAgZQAAgTgRAAQgMAAgPAMgADKhVQAAAngwBBIAGACQAJgMALgPQAMgTALgTQAKgVAIgVQAHgVAAgRQAAgIgFgGQgFgEgJAAQgHAAgHACQgHAEgJAHIgTARIARgBQAZAAAAAcgAhPgKIBRgBIAHgKIgvgBQgLAEgeAIgAgphGIANgVg");
	this.shape_4.setTransform(105.9,-8.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFF00").s().p("AimCcQgVAAgFgQQgDgJABgMIgBgFQgCgMAAgMQAAgQAGgSQAGgTALgOQAKgRAOgIQAMgLAQAAQASAAAIALQAJAIABANQABAMgHAMQgHALgPAAQgIAAgEgCQgEgCgJAAIgEAAQgLAMgLAOQgMATgFASIgBADIAAABQAEAQARAKIADABIAQgMIAwgqIAhgeIAcgkIApg1QAXgdAXgZQAWgbAUgUQATgTAPgHIBDgBQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABQAAAEgNARIgpA3QAEAAAEgCIgbAcIgLAPQg2BJgZApQgZApAAAQIAAADQArgcBNhYIAGAGQhPBWgtAdQADADAIAAQAKAAAUgPQASgRAWgVIArgsQAWgWAPgNQADABAAAEIAAABIgCAEIhEBKQgaAbgRANQgRAOgMADQgMAEgNAAQgJAAgHgEQgKAEgHAAQgWAAAFgfQAEgdATgeIAGgNQAMgeAdgmIgLAKIgqAnIgJAJIgYAhQgXAfgYAXIgVASQgJAHgRACQgJAAgGgCgAi5CNQABAIAIABQgGgFgEgHIABADgAghCGQgDAPAPAAIAHgBIgDgEQgJgIgCgOQgFAHAAAFgAhwB1QgQAQgKAIIAOgIQAJgHAIgJIAQgTIgVATgAA0hAQggAlgYAjIAXgXQAQgPAPgNIBIhfQgmAkggAmg");
	this.shape_5.setTransform(75.5,-9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFF00").s().p("AjACYQgKgIgFgJQgFgJgCgMQgCgMAAgMQAAgQAGgSQAGgTAKgOQALgRANgIQANgLAPAAQATAAAHALIABAAIAEACQADACgBAFQADAGABAGQABAMgHAMQgHALgPAAIgMgBQgJAQgCAOQgCAPAGALQAFAKAOABIACAAIATgUIARgUIAXgaQANgNAPgMIAMgKQgKgEgDgPIgCgIQgGgEgDgHQgLgYACgYQAAgRAMgRQANgSAUgMQATgMAVgHQAYgGAaACQAXACANAJQANAJAGALIAYghIBCgBQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABQAAAEgNARIhHBgQg2BJgaApQgPAbgFAPQAQADACAEIgVAAIgBAIQAAALAOAAQAJAAATgPQAUgRAVgVIAqgsQAWgWAPgNQAFABAAAEIAAAAIgCAFIhFBKQgaAbgRANQgQAOgNADQgMAEgNAAQgRAAgLgNQgJgKAAgSQgEgIgBgMQAAgqAdgqIgBAAQgHAFgHABQgLAHgPAKIgKAGIgIAHIgmAoIgqArIgUASQgJAHgSACQgNAAgIgGgAi5A9QgLAKgFAQQgEAOAEAQQAFAQARAKQATAGAQgPIAIgHIgEgBQgRgCgFgPQgFgPACgUQABgMADgMQgMABgMAKgAghAIQAAAGAHADIAPgJQgNgBgKgGIABAHgAAAg3IgRAWIABAJQADAQANAHQAHAEAOgCQANgJAMgRIAPgXQASgbgGgOQgBgLgMABQgZAAgjAsgABQhZQAEAPgHAPIAUgXIASgbQgFgNgNgLQgNgJgPAAQgVABgRANQgRANgMARQgFALgFALQAggcAkAAQARAAADAPg");
	this.shape_6.setTransform(21.3,-9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFF00").s().p("AkAEkQgMgOAAgYQAAgNAEgRIAAgOQADgpA1hOQA8hYA8hQQAxhDA2gvIAOgNIAagYQAYgVATgIQATgIAQgCQARgDAPACQAOABAPgDQAPgBATgIQASgIAXgUQgHAwgXAdIACABQgNAfgPAMQgUANgugDIgbgPQguAAgZAEIgRALQgeAbgXAeQgZAegVAeIgoA5QgSAZgPAUQARgQASgLQATgKASgGQARgDAOgBIAZgCQAPAAAOAOQANARAAATQAAAqgYAwQgXAvgmAmQgmAngtAZQguAZgqAAQgSAAgMgQgAjiEqQAGAAAHgCQgSgBgLgKQABANAPAAgAhqA/IgGAHQgYAagXAhIgLAOQgxBJgDApQgDAcAQAAQAQAAAVgOQAigfAug/IADgDQAphGAEgrQACgVgTAAQgVAAgYAXgAgQAyQAGgPAAgLQAAgOgPgCIgCAAQgQAAgWARIgJAHIAPgBQAaABARASg");
	this.shape_7.setTransform(1,-23.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFF00").s().p("AhDCcIgGAAQgbAAgSgXQgSgXAAgjQAAhVBfhKQASgPAUgNQASgMATgKQATgKARgFQAQgGALAAQASAAALALQALALAAARQAAAUgRAWQgRAXgaAOQgVALgZAJQggAUg2AZQgnA4AAAcQAAARAHAJQAIAFAKAAQAOAAAYgJIAQgHQApgiA9hVIAHAGQgpA3ghAjQAagSAagYQAbgbAUgeQAAAAABgBQAAAAABAAQAAAAAAAAQABAAAAAAIABAEIAAABQAAADgKASQgLASgYAZQgrArgmAVQgSAHgQAFQgOAHgMAAgAgigCIgOARIAvgWIghAFgAAKg3QgSAWgRATQARgEAPgIQAagOAWgRQARgNANgPIAAgCQAAgLgMAAQgUAAgrArgAAhhtIgVAYQAhgVAdABQAPAAAEAKQAOgTAAgQQAAgNgOAAQgXAAglAig");
	this.shape_8.setTransform(-32.2,-8.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFF00").s().p("ABbCdQgTgBgLgLQgLgKAAgVQAAgSARghQARghAagfIBAhPQANgOAGgNQgDgCgEAAQgnAAhDBSQgWAaglAvIhEBoQgBAEgFAAIg9AAQAAAAgBAAQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgEABgBIBiiSIAkg2IAYgnIAIgPQgiAMg2BEIhsCDQgFgCgHgBIghAxQgDADgFAAIg2AAQgFAAAAgDIBrimIgDAEIgGgFIAug6IA1hRIA8AAIgfA0QADAGABAHIARgSQARgTAOgLQAOgLAKgDQAKgDAMAAQAOAAAKAKQAKALAAAQQAAAMgFAMIgEAOIgBAJQBGhUAuAAQARAAALALQAMAMAAASQAAAUgOAbQgOAageAoIhEBVIgOASIAGAAQArAABbh2IAGAFQheB4gvAAIgIgBIgCAEQgIAMAAAIIABAGQABACAIAAIAMgEQANgEATgOQATgNAagYQAagYAfgoQACgCADADQADACAAADQAAAGgSAXQgSAXgZAYQgaAXgdASQgbASgVAAIgDAAgAAdh/QgQALgSATIgXAXQgCASgJARQA8hCAigKIABgCQAEgKAAgFQAAgHgHAAQgIAAgQAMgABXgxIALgLIABgCQA1g3AiAAIALABQACgHAAgHQAAgKgIAAQgIAAgPALQgPALgSASQgSARgSAVIgMANg");
	this.shape_9.setTransform(-66.5,-8.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFF00").s().p("AC/G3IgDgbIgBgXIABghQAAgQADgQQgVgBgQgJIgGAAQgRAAgTgEIg6gLQghAQgbAAQgYAAAAgMQAAgJAOgGQAPgGAVAAIAPABIAWADQAcgTAdgsIAAgCQAAgWAKgfQAKgfAQgkQAQgkATgmQAGgKAEgJIgSAAQgVAEgTALQgdAPgaAYQgOAMgMAOIgBABIgGAHIgJAMIgsA+IgMANQgQAVgRAUQgVAagZAQQgmAcghAMQgjAegfAVQgfAUgSADQhMAghZgLQhZgMglgxQiMgRghhrQgjiCBfhrQA4hDBdgmIA0gTQAOgFAHAAQAIgBAMgEQALgFAKAAQAJgBAEACQAEACAAAEQAAAEgLAGIgqAHQirAshEB4Qg5BWAcBaQAEAQAKAVQAKAUAmAcQAmAdAuAFIgHgbQgghrA8h7QA3htBhhTQBRg2BagZQCrgtAgBzQAdBchPB3QgzBWhiBDQhIAxhNAcQAcAKAcABQAzACAogWQAngWAkgiQAkgjAlgqQAkgrAugnQAsgoA8geQARgJASgFQgXgMgSgSQgRgRgMgVIgEgFQgagegIglQgHgmAJgeQANglAegeQAfgfAogWIAigSQAbgUAcgRQAlgVAngOQAngOAjgEIANAAQArAAAjAMQAjAMAZAXQAIAHAGAHQAogXAcAAQAMAAAAAIQAAAGgGAAIgEAAQgFAAgCgBIgBAAQgUAAgcAQIgHADQAKAOAHASQAJAWADAZIAEAAQApAAAfAPQAfAPAWAXQAWAYAKAcQALAdAAAcQAAAYgHAYQgHAYgLAVQgLAUgRAOQgPAMgTAEQAogQAQgjQAQgkAAgtQAAglgLggQgLgfgVgWQgUgVgbgMQgbgMggAAIgHABIABARQAAAigKAmIgIAaQgEAggOAWQgMATgPAKIAUgcQAPgcAKgbIAAgHQAAgUgCgSIACgfQAAgVgCgSIgUAEIACAFQANAaAFAjQgFgjgNgaIgCgFIAUgEQACASAAAVIgCAfQACASAAAUIAAAHQgKAbgPAcIgUAcIgGAEIgNAGIgCABQgJADgJAAIgBAAIAAAAIgCAAIgDAAQgTgDgPgMQgOgMgHgVQgCgJAAgLQAAgOAFgRQAFAoARAKIABAAIAAABQAKAFAKAAIAAAAIAAAAQAIAAAIgDIAAAAIABAAQAUgIAPgVQAQgWACgXQACgMAAgLQAAgdgKgXIgDgIIgZAKQgpARgjAdQgMAKgLAKIgHAPQgSAggNAdIgUAsIAAABQAAAfARAOQARAQAXAAQAaAAAcgSQAYgPAXgaQgXAagYAPQgcASgaAAQgXAAgRgQQgRgOAAgfIAAgBIAUgsQANgdASggIAHgPQALgKAMgKQAjgdApgRIAZgKIADAIQAKAXAAAdQAAALgCAMQgCAXgQAWQgPAVgUAIIgBAAIAAAAQgIADgIAAIAAAAIAAAAQgKAAgKgFIAAgBIgBAAQgRgKgFgoQgFARAAAOQAAALACAJQAHAVAOAMQAPAMATADIADAAIACAAIAAAAIABAAQAJAAAJgDIACgBIANgGIAGgEIgBABQgOASgUARQgTAQgWANQgWAMgXAAQgJAAgMgEQgLgDgKgIQgKgJgHgLQgEgIgBgKIg7B+QgOAegVAfQgVAfgbAdQgYAbgbAYIAAAOQAAAbAMARIAQAAIAdgBQAIgUAMgXQATgjAagfQAageAigVQAhgVAnAAQAVAAAMAMQAMANAAARQAAAhgVAeQgWAfgiAXQgiAXgrAOQgsAOgrAAQgDADgDAUQgDAUAAAYIABAYQABAMADAMgAk8F4QA1gQA1goQgSAFgPACQgSACgOgBIgjgBIgMAAIgbgBQgXgDgUgFIgPgEIgeAJQg/ASgtgDQBhBQCEgqgAjcjAQgSAGgUACQgSAMgKADQh9ArhTBtQhTBrgHB3QAAAVACAYIAFAsIAHAXQAtACBFgOIAWgGQgOgGgMgJQgcgUgQgfIgHgSIgBgBQgRghgEgpQgFg5AXg0QAWgyArgoQAqgnA7gYQA7gXBCAAQAxAAAgATQAhAUANAfQAOAfgHAmQgIAkgfAjQgDATgHASQgJAUgNASIANgPQBrhrADhpQABgcgFgSQgVhIhWAAQgfAAgoAJgAEDEWQAAAGgKAGQgLAGgRAFIgPAFIgDALQAXAAAagFQAagGAagKQAagKAYgPQAXgOATgSQASgSALgVQALgWAAgYQAAgNgHgKQgHgKgTAAQgbAAgeAQQgeAQgcAbQgdAagWAkQgQAZgKAbIACgBQAOgEAUgLQAEgDAEAAQABAAABAAQABABAAAAQABAAAAABQAAABAAAAgAC4E2IgKACQAKAEAJABIADgJIgMACgABLEgIA3AHIAEAAIAAgBQgLgPgFgUQgVAQgWANgAlogtQgrAUgiAfQgMALgKANIgMAgQgSA3AGA7QADAeAOAZQANAYAVAUQAMALAQAIQAggLAYgNQBbglBKhDQgQALgTAJQgbAMghAAQgXAAgSgGQgSgGgMgKQgMgJgHgNQgGgMAAgPQAAgNAFgNQAGgNANgNQANgNAVgMQAVgLAegKQgTAIgSAJQgSAMgOANQgOANgIAPQgIAPAAAPQAAAWAVARQAWARAlAAQAXAAAZgJQAZgKAWgSQAVgRANgXQAGgLAEgLQgNALgGAAQgFAAAAgFQAAgFAKgHQAKgIAIgJIAAgHQAAgagIgWQgJgUgQgRQgQgQgZgLQgZgKgfAAQgvAAgqAVgAjWhEQAaAIATASQATARALAZQAKAUABAaQALgRAIgRQAMgjgJggQgLgggegUQgfgVg0AAQg3AAgxAZQgyAagjArIgTAbIAFgEQAZgVAcgPQAdgPAcgHQAdgJAZAAQAdAAAaAKgACXAHIgDACIALgEIgDgBIgFADgACnAAQAKABAKAAIACAAIAKAAIAJgMQgWAEgTAHgAB8gWQALAJANAGQAXgIAagFQgigBgbgIQgSgGgQgIQAJALANAKgAEKleQgoAMghAXQgYARgVAeQgUAegNAhQgNAigCAiQgBAiAOAZQAPAZAhAOQAXAIAjgBIAJgOIAqhGIAlg6IAagoQAKgPAAgCIAaAAQAfghAmggIAmgfQgXgPgdgJQgmgKgoAAQgoAAgoALgAImiZQgQApgaAeIgFAIIAFgIQAageAQgpQALgdAEgeQgEAegLAdgAHVkmQgSAXgTAdIgQAYIAPgKQAbgUAbgMQAVgLATgGQgOgYgVgRIgVAYgAH6lLIgCACQAXATAPAcIAWgEQgCgRgEgOQgHgYgKgRQgSAMgRAPgAGhl1QApALAhAXQAXgSAVgNIgBAAQgOgVgSgLQgTgMgTgGQgTgGgSgCIgegBIgQAAQgfAAghAOQgiAOghAYIgLAIQArgLAsgCIAPAAQAnAAAlAJgAIKhUg");
	this.shape_10.setTransform(-154.4,-24.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-260,-86.8,545.6,142.9);


(lib.text2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#990099").s().p("AhPB4QAAgHAFgGQAGgGAHAAQAKAAAAAJQAAAHgGAGQgHAGgHAAQgIAAAAgJgAg1BZQAOgYAagwIAnhRQAhhAARAAQAEAAABAHQAAAZgoA4Ig4BJQgQAcgVAeg");
	this.shape.setTransform(129.5,-1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#990099").s().p("AgHAfIgUAVQgMANgNAAQgJAAgGgKQgEgJgBgKQAAgSAKgPQANgSAbgXQAegaASAAQAOAAgEATIALgPIAUAAIgnA6QgaApAAAPQgBAIAKAAQAPAAATgZQAOgSAKgTIADAAQgeBBghAAQgQAAAAgigAgagQQgiAtAAAXQAAALAJgBQASABAhgyQAigtAAgVQAAgJgIAAQgUABggAtg");
	this.shape_1.setTransform(110.6,6.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#990099").s().p("AgCA8QgGgHABgHQgBgJAIgOQAHgOAAgGQAAgDgDgDQgIAAgHgDIguBEIgTAAIBQh/IAUAAIgSAdIAXgRQAPgKALAAQASAAAAANQgBAEgCADIgFAFQAAAAgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQADgGAAgGQAAgHgHAAQgOAAgVASQgTAQgIAPIAPAIQAGAJAAAIQAAAJgHANQgGAOAAAHQAAAHAHAAQANAAAXgbIAeglIADAAQgwBCgUAAQgIAAgDgGg");
	this.shape_2.setTransform(97.4,6.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#990099").s().p("AgKA9QgEgHAAgHQAAgTAOgdQgIAFgIAAQgRAAgDgSQgBgGABgGIAAgCIgcAkIgDgBQAVgdAJgJQAGgTAGgIQAFgIAHAAIAGAFQABAGgFAIQgFAIgQALQgBAIABAHQABAGAFAFQAEACAHAAQAJAAAJgFIABgCIALgQIAYgjIAUAAIgTAdIgUAcQgYAoAAARQAAAIAIAAQAMAAAWgaIAPgTIAMgSIADAAQgoBCgcAAQgFAAgFgGgAAAgBIAFgCIgCgCIACACIgFACIADgEIgDAEIAAAAgAAAgBIAAAAg");
	this.shape_3.setTransform(87.4,6.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#990099").s().p("AgsA2QgJgKAAgNQAAgNAFgLQAHgRAggaQAggcATAAQAMAAAAANQAAAXgdAQQgVALgZACQgTAXAAAUQAAAHAFAFQAGAGAHAAQAPAAAXgZIAjglIADAAIgjAnQgYAagQAAQgNAAgKgLgAAIgkIgbAkQATgCAWgRQAagSAAgSQgBgHgFAAQgMAAgWAag");
	this.shape_4.setTransform(75.8,6.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#990099").s().p("AAHA6QgEgGAAgJQgBgSALgQIAFgIIgpAAIgKAPIgfAtIgTAAQBGhiAAgQQAAgIgKAAQgJAAgXAaIgJAKIgUAZIgEAAIAUgZIAMgMQAYgbANAAQARAAAAAWQAAAGgEAIQgCAJgIALIgFAIIAqgBIAOgUIAGgJIAJgNIAIgLIAGgKIAUAAIgGAKIgJAMIgJAOIgIALIgMASIgNAUQgGAKgDAJQgEAIAAAHQAAAHAJAAQANAAAWgaIAJgLIAUgZIACAAIgTAZIgKAOQgYAagPAAQgJAAgFgHg");
	this.shape_5.setTransform(62.8,6.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#990099").s().p("AgrA2QgKgKAAgNQAAgNAEgLQAIgRAhgaQAfgcASAAQANAAAAANQAAAXgcAQQgWALgZACQgTAXAAAUQAAAHAGAFQAEAGAHAAQAQAAAYgZIAhglIAEAAIgjAnQgYAagRAAQgNAAgIgLgAAIgkIgcAkQAUgCAWgRQAagSgBgSQABgHgHAAQgKAAgXAag");
	this.shape_6.setTransform(48.8,6.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#990099").s().p("AkpCrQgSgPAAgaQAAgiAdggQAeghAkAAQAkAAAAAYQAAAPgHABIgEgDIABgEIADgFQABgEAAgFQAAgRgeAAQgkAAgbAgQgcAfAAAhQAAAZAQAOQARAPAbAAQAwAABBg6QAfgaAagfQAaggAXgkQAshIAAguQAAgagegEQACAKAAALQAAAxgsA3QguA4g0AAQgMAAgHgIQgHgHAAgLQAAgzAzg1QA2g2A5ABQgNgggoAAQg5AAg6A4QgYAWgSAaQgSAbgPAdIgCgCQAPgfATgaQATgaAXgWQA6g4A6AAQAqAAAOAjQAsAFAAA5QAAAegMAlQgGATgMAWQgNAZgSAWQBPhGAggvIATghIAbgvQAWgiAKAAQAFAAAAAFQgBASggAlQgmAtgFAIQhYCfgFAXQAbgtAfgnQAegoAhghQARgSAZgTIAwgjQAXgTAYgOQAZgNATAAQAZAAAAAeQAAAMgGACIgCgDIACgJIABgKQAAgTgVAAQgoAAg6A6QgZAagXAeQgXAcgUAkQgoBHAAAkQAAANAEADQAFADAFAAQARAAAlgmQAZgZAVgcIADACQglAugZAXQgZAXgQAAIgGAAQgEAAgDgCQgEgDgEgFQgDgGgCgMQgCgUAFgWQAFgWALgVQAKgVAPgVQAOgSAQgSQAQgSAPgOIAYgWIAEgDIgEADIgMAKIgVARIgZAYQgPANgSASQgQASgQAVIggAqIgbArQgNAVgKARIgHAAIBijCQgmAngcAeQgfAdgZAVIACgCIACgCQgUASgUAQQgUAQgYANQg+AlgyAAQgdAAgSgPgAiBhgQg0A0AAAxQAAAZAZAAQASAAAbgQQAUgNASgOQAWgWAQgeQAQghAAgcQAAgLgDgLIgBAAQg3AAgzA0gABZhDQAHgGAKgMIAVgbQAZgjACgLIgBgBQgSAAguBcg");
	this.shape_7.setTransform(28.5,-3.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#990099").s().p("AAEA9QgEgHABgKQABgJACgKQADgJACgFIADgFIADgFQgFAEgEACIABAAQgNAEgMAMQgMALgJALIgLANQgFAFgEACIgFABIgFAAQgIgBgDgKQgEgJABgMQAAgNAFgNQAFgKAJgJQAJgCADADQACADgBADQgLAHgGAIQgGAJgDAJQgCAIAAAIQABAHACAFQACAFAEACQAFABAFgDQAEgBAFgHIAMgPIAQgQQAJgIAKgGQgSAAgDgSQgCgIAGgMQAHgNAKgJQAEgFAGgEQAJgEAJgCQAIgBAHACQAHADAAAIIAAAGIgCAGIAEgGIAFgHQAKgFALADIgmA5QgbAoAAARQAAAIAKAAQANAAAWgaQAQgTALgTIAEAAQgqBDgbAAQgKAAgCgHgAAAglQgJAMgDAKQgEAKACAFQAAAIAKAAIAEAAIAAgBIAAAAIADgBIAAAAQAJgEALgMIAGgJIAHgLIAGgOQADgHgBgEQgBgIgKAAQgSAAgPAag");
	this.shape_8.setTransform(-25.9,6.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#990099").s().p("AhGAeQAAgdAfgfQAfgiAaAAQAQAAAAATQAAAVgNAZQAFAFAGAAQASAAAUgaIABADQgSAbgVAAQgHAAgGgGQgkA9gdAAQgYAAAAgjgAgfgRQgcAnAAAaQAAAOAMAAQAaAAAjg9QgEgDAAgEQAAgMAOgBQAHgOAAgOQAAgPgMAAQgWAAgcAtg");
	this.shape_9.setTransform(-38.9,6.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#990099").s().p("AAjA4QgDgHAAgJIAEgTIAEgOQAGgJAKgNQAKgOAOgXQgDgCgGAEQgFADgHAIIgPARIgPATIgMAQIgIAMIgGAIIgHANIgJAKQgEAFgDABQgFAAgCgDQgCgBAAgDQgBgCAAgEIAAgGQABgKAFgNQAGgNAHgMIAOgaIAPgWQgHABgLALIgYAbIgaAfIgWAcQgKAMgHAEQgGACgHAAQgHgBgEgJQgEgJAAgMQAAgMAFgNQAEgLAJgIQAKgDACACQADADgCAEQgKAHgGAJQgGAJgCAJQgDAHABAIQAAAHADAFQAGAKAKgGQAHgCAHgJIAPgTIAQgWIASgVQARgUANgKQAKgLAMgGIARAAIgTAgIgUAfIgOAeQgGANAAAHQAAAEADAAIAGgHIALgQIAPgWIARgVIAJgMIAMgOQAHgIAIgHQAIgGAIgDQAHgCAEAAIALABIgUAcIgTAcQgbAoAAASQAAAHAKABQANAAAWgaIAQgTIANgSIAEAAQgVAggSARQgSAQgOABQgJAAgDgIg");
	this.shape_10.setTransform(-56.6,6.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#990099").s().p("AhGAeQAAgdAfgfQAfgiAaAAQAQAAAAATQAAAVgNAZQAFAFAGAAQASAAAUgaIABADQgSAbgVAAQgHAAgGgGQgkA9gdAAQgYAAAAgjgAgfgRQgcAnAAAaQAAAOAMAAQAaAAAjg9QgEgDAAgEQAAgMAOgBQAHgOAAgOQAAgPgMAAQgWAAgcAtg");
	this.shape_11.setTransform(-81.4,6.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#990099").s().p("AAiA6QgFgHAAgIQAAgSAPgVQABgDAagbQAPgRAAgKQAAgJgKAAQgRAAgqA1QgNAPgkA3IgTAAIAog6QAcgpAAgPQAAgIgKAAQgUAAhTB6IgTAAIApg7QAggtAAgJQAAgJgJAAQgKAAgWAaIgcAjIgEAAIAeglQAWgbANAAQAHAAAFAFQAFAFAAAIQAAALgHANIAXgaQAQgQAMAAQAQAAAAAVQAAALgEAMIAXgbQARgRAMAAQAUAAAAASQAAATgbAiQgbAkAAAJQAAAKAJAAQANAAAVgaIAdgkIADAAQgWAdgIAKQgXAagQAAQgIAAgFgHg");
	this.shape_12.setTransform(-98.9,6.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#990099").s().p("AiaCuQgSgPAAgaQAAghAdghQAeghAkAAQAkAAAAAZQAAAOgIACIgEgEIACgDIACgGQACgDAAgGQAAgRgfAAQgjABgcAgQgbAeAAAhQAAAZAQAPQAQAPAcgBQAogBAmgXQAlgWAhgkQAiglAcgsQAdgrAUgvQAFgNAEgMQADgLAAgMQAAgNgFgJQgGgMgLgBQACALAAAPQAAAQgZAsQgZAsgiAdQgmAhgeAAQgLAAgHgHQgHgIAAgLQAAgzA6g8QA7g7A2AAQgLgfglAAQg1AAgzA5QgsAtgaA8IgDgBQAeg/ApgrQA0g6A2AAQAmAAAOAiQASADAIAZQAGAQAAAZQAAAUgGAXQgHAXgLAVQgMAXgRAXQgQAVgUATIgNANIgVARIgZATQgMAJgKAGQg9AlgyAAQgdAAgRgPgAAZhdQg3A6AAAzQAAAYAYAAQAagBAtgoQAPgPANgPQAMgQAKgRQAYgoAAgjIgCgLIgBAAQg0AAg7A5gAAeBWQgEgBgDgDIgGgIIgJgLQgEgCgEAAQgGABgIAGQgJAFgMALIABgEIALgJIANgLQAIgFAFgDQAGgCAGACQAKANAFAFQAGAFADABQAMACAOgPIAGgGIAQgSIADAAQgmAvgTAAIgDAAg");
	this.shape_13.setTransform(-120.9,-4.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-154.9,-30,310,60.1);


(lib.text1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AgDBJQgGgIAAgJQAAgLAJgRQAIgRAAgIQAAgDgDgDQgLAAgHgFIg4BTIgYAAIBiiaIAZAAIgXAjIAcgVQATgMANAAQAVAAAAAQQAAAFgDADIgGAGQgCACgDgBQgCAAAAgEQAEgIAAgHQAAgIgJAAQgRAAgbAWQgVATgMASQAPAHAFAEQAHALAAAJQAAALgIAQQgJARAAAIQAAAIAKAAQAPAAAdggQAFgGAggnIADAAQg6BQgZAAQgJAAgFgHg");
	this.shape.setTransform(98.3,42.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AhWAkQAAgiAmgnQAlgpAhAAQATAAAAAXQAAAagQAeQAHAHAIgBQAWAAAYggIABAEQgXAhgZAAQgIAAgIgHQgsBKgjAAQgeAAAAgrgAgmgVQgiAwAAAgQAAARAOAAQAgAAAshMQgFgCAAgGQAAgOARgCQAIgRAAgQQAAgTgPAAQgbAAgiA3g");
	this.shape_1.setTransform(87.1,43);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF0000").s().p("AAKBHQgHgJAAgKQABgVALgUIAHgJIgzAAIgMASIglA2IgYAAQBWh4AAgTQAAgJgNAAQgLAAgcAfIgKANIgZAeIgEAAIAYgeIAOgQQAdggAQAAQAVAAAAAbQAAAGgEAKQgEALgJAOIgGAKIA0gBIAQgZIAIgLIAKgPIALgPIAGgLIAZAAIgIALIgKAQIgLAQIgJAOIgQAXQgJAMgGAMQgHALgEALQgFALABAIQAAAIAKAAQAQAAAbgfIALgOQAIgLAPgTIAEAAIgYAeIgNARQgcAggTAAQgKAAgFgIg");
	this.shape_2.setTransform(69,42.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF0000").s().p("AhLBiQgLgNABgPQAAgRAEgMQAKgXAngeQAogiAWAAQAPAAAAAQQgBAbghARQgZAPghAFQgXAcAAAXQAAAJAGAHQAHAGAIAAQATAAAegeIAogvIAFAAIgrAxQgdAggVAAQgPAAgMgNgAgJgMIgkApQAZgCAagVQAfgUABgWQAAgIgIAAQgOAAgZAggAA4hXQAAgJAGgHQAHgHAIAAQAKAAgBALQAAAJgFAHQgHAGgJAAQgJAAAAgKgAAAhPQgDgDgBgEQABgJAEgIQAHgHAIAAQAJAAAAAKQAAAJgFAHQgFAHgKAAQgDAAgCgCg");
	this.shape_3.setTransform(54.1,39.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF0000").s().p("AAqBGQgGgIAAgKQAAgWASgZIAgglQATgVAAgMQAAgLgMAAQgVAAgzBBQgQATgsBCIgYAAIAyhGQAig0AAgRQAAgJgMAAQgZAAhlCUIgXAAIAyhHQAmg3AAgMQAAgKgKAAQgMAAgbAfIgiArIgFAAIAlguQAaggAQAAQAIAAAGAGQAGAHAAAIQAAAOgHAQIAbggQAUgTAOAAQAVAAAAAaQAAAMgGAPIAcggQAVgVAPAAQAXAAAAAWQAAAXggApQghAsAAAMQAAALALAAQAQAAAagfIAjgsIADAAQgaAkgKALQgcAggTAAQgKAAgGgJg");
	this.shape_4.setTransform(32.8,42.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF0000").s().p("AhWAkQAAgiAmgnQAlgpAhAAQATAAAAAXQAAAagQAeQAHAHAIgBQAWAAAYggIABAEQgXAhgZAAQgIAAgIgHQgsBKgjAAQgeAAAAgrgAgmgVQgiAwAAAgQAAARAOAAQAgAAAshMQgFgCAAgGQAAgOARgCQAIgRAAgQQAAgTgPAAQgbAAgiA3g");
	this.shape_5.setTransform(12.1,43);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF0000").s().p("AgDBJQgGgIAAgJQAAgLAJgRQAIgRAAgIQAAgDgDgDQgLAAgHgFIg4BTIgYAAIBiiaIAZAAIgXAjIAcgVQATgMANAAQAVAAAAAQQAAAFgDADIgGAGQgCACgDgBQgCAAAAgEQAEgIAAgHQAAgIgJAAQgRAAgbAWQgVATgMASQAPAHAFAEQAHALAAAJQAAALgIAQQgJARAAAIQAAAIAKAAQAPAAAdggQAFgGAggnIADAAQg6BQgZAAQgJAAgFgHg");
	this.shape_6.setTransform(-4.5,42.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF0000").s().p("AgsBrQAAgRAEgPQgTAbgIAHQgUAWgQAAQgTAAAAgeQAAgZAagoIApg6IAYAAIguBEQghAzAAASQAAAMAMAAQARAAAvhBQAPgVAng/IAYAAIguBEQggAzAAAUQAAAKAMAAQAQAAAZggQAUgXAMgXIAFAAQgyBSggAAQgSAAAAgYgAAshaQAMgGAKABQAJAAAHgCQAOgHAXgZIADgBQgbAmgaAMQgIAEgLgBQgKAAgHADQgQAIgTAXIgEABQAggpASgHg");
	this.shape_7.setTransform(-24.6,37.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF0000").s().p("AhrBEQgHgIAAgJQAAgaAZgnIANgUIAegrIAYAAIgvBGQghAxAAAVQAAAJAMAAQAYgBAagiIAFgGIgGgCQgLgFgFgIQgEgIADgIQACgKAKgIQAPgDAJAGQAJAFADAKQADAJgDAOIgCADIACgBQALgCALgJQAIgGAIgIIAIgOIAOgUIAegrIAYAAIgvBGQghAxAAAUQAAAKAMAAQAPAAAbgfIASgXIAPgVIAEAAQgyBPghAAQgJAAgGgIQgFgIAAgJQAAgRAKgXIgJAHQgNAKgLACIgDABQgEAJgIAHQgOANgQAJQgRAIgNABQgOgCgHgIgAgrgOQgLAIgBAHQgBAKAGAHQAFAHALADIABAAIAFgLQADgLAAgHQAAgIgEgEQgCgDgEAAIgIACg");
	this.shape_8.setTransform(-46.1,43.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FF0000").s().p("AAFBEQgEgIABgMQABgLADgMQADgLADgGQAGgLAMgQIAegtQgIAAgOAOQgOANgQATIgdAlIgaAiQgNAPgJAEQgHAEgIgCQgJgBgFgLQgEgLAAgPQABgPAGgQQAGgOALgKQALgDADAEQADADgBAFQgNAKgIAJQgHAKgDALQgEAKABAJQAAAJADAGQADAGAFACQAGACAGgDQAHgEAJgKIATgWIAVgcIAVgaQAUgYANgMQANgLAPgHQANgGANAEIgXAiIgYAjQggAxAAAVQAAAJALAAQAQAAAbgfQAUgXANgVIAEAAQgyBPgiAAQgLAAgDgJg");
	this.shape_9.setTransform(-65.8,43.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FF0000").s().p("AgLA1QAAgRAFgPQgUAbgHAHQgVAWgQAAQgSAAAAgeQAAgZAZgmIAqg8IAVAAIgsBGQghAxAAASQAAAMAMAAQASAAAuhBQANgTAphBIAYAAIgvBGQgfAxAAAUQAAAKAKAAQAQAAAbggQAUgXANgVIAEAAQgyBQgiAAQgQAAAAgYg");
	this.shape_10.setTransform(-83.5,43.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FF0000").s().p("AArBFQgEgJABgMQABgLADgLQADgMADgFQAGgMAMgQQANgRARgcQgEgCgHAEQgGAFgJAJIgSAVIgSAXIgPAUIgJAOIgIAKIgJAPIgLAOQgFAGgDgBQgGABgDgCQgCgCgBgEQgBgDABgEIAAgHQABgNAGgQQAHgQAJgOIARggIASgbQgJABgNAOQgNANgQAUIggAlIgaAiQgNAQgIADQgIAEgIAAQgJgBgFgLQgFgLABgPQAAgOAFgQQAFgOAMgKQALgEADADQADAFgBAEQgNAIgHALQgIAMgCAKQgDAJABAJQAAAIADAGQAHANANgHQAIgDAIgKIATgXIAUgbIAWgaQAUgZAPgNQANgMAPgIIAUAAIgXAoIgYAmIgRAkQgHAQgBAIQAAAFAEAAIAIgIIANgUIATgbIAUgaIALgOIAPgSQAJgJAJgIQAKgIAKgDQAIgDAGgBIAMACIgXAiIgYAjQggAxAAAVQAAAJALAAQAQAAAbgfIATgXQAKgMAGgKIAFAAQgZAngXAVQgWAUgQABQgMgBgDgIg");
	this.shape_11.setTransform(-104.6,43.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FF0000").s().p("AgLA1QAAgRAFgPQgUAbgHAHQgVAWgQAAQgSAAAAgeQAAgZAZgmIAqg8IAVAAIgsBGQghAxAAASQAAAMAMAAQASAAAuhBQANgTAphBIAYAAIgvBGQgfAxAAAUQAAAKAKAAQAQAAAbggQAUgXANgVIAEAAQgyBQgiAAQgQAAAAgYg");
	this.shape_12.setTransform(127.6,-27.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FF0000").s().p("AgtBrQAAgRAGgPQgUAbgHAHQgVAWgQAAQgSAAgBgeQAAgZAZgoIArg6IAXAAIgvBEQggAzAAASQAAAMAMAAQARAAAvhBQAPgVAmg/IAYAAIgsBEQghAzAAAUQAAAKAMAAQAQAAAYggQAVgXANgXIAEAAQgzBSgfAAQgTAAAAgYgAArhaQANgGAKABQAKAAAFgCQAPgHAXgZIAEgBQgcAmgZAMQgJAEgKgBQgLAAgHADQgQAIgSAXIgFABQAggpARgHg");
	this.shape_13.setTransform(105,-32.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FF0000").s().p("AhrBEQgHgIAAgJQAAgaAZgnIANgUIAegrIAYAAIgvBGQghAxAAAVQAAAJAMAAQAYgBAagiIAFgGIgGgCQgLgFgFgIQgEgIADgIQACgKAKgIQAPgDAJAGQAJAFADAKQADAJgDAOIgCADIACgBQALgCALgJQAIgGAIgIIAIgOIAOgUIAegrIAYAAIgvBGQghAxAAAUQAAAKAMAAQAPAAAbgfIASgXIAPgVIAEAAQgyBPghAAQgJAAgGgIQgFgIAAgJQAAgRAKgXIgJAHQgNAKgLACIgDABQgEAJgIAHQgOANgQAJQgRAIgNABQgOgCgHgIgAgrgOQgLAIgBAHQgBAKAGAHQAFAHALADIABAAIAFgLQADgLAAgHQAAgIgEgEQgCgDgEAAQgEAAgEACg");
	this.shape_14.setTransform(83.4,-27);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FF0000").s().p("AhvCYQgKgJAAgNQAAgcAwhJQAuhGA0g5QA7g/AbAAQALAAAAAMQAAAfg2AyQgzAughAHIg1BOQgmA8AAATQAAAGAFAGQAFAEAGAAQAeAAAyhGQgCgFAAgGQAAgPALgXQAJgbAOAAQAEAAAAAFQgBAJgNAbQgLAXgGALQAIAKAIAAQARAAAPgRIAFAAQgQAUgVAAQgJAAgJgJIgkAsQgaAbgUAAQgNAAgIgKgAAphkQgMAQgpBAQAXgFA0gyQA3g0AAgXQAAgJgKAAQgWAAgtA7g");
	this.shape_15.setTransform(69.5,-35.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FF0000").s().p("AgLA1QAAgRAFgPQgUAbgHAHQgVAWgQAAQgSAAAAgeQAAgZAZgmIAqg8IAVAAIgsBGQghAxAAASQAAAMAMAAQASAAAuhBQANgTAphBIAYAAIgvBGQgfAxAAAUQAAAKAKAAQAQAAAbggQAUgXANgVIAEAAQgyBQgiAAQgQAAAAgYg");
	this.shape_16.setTransform(50.2,-27.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FF0000").s().p("Ag7BDQgLgLAAgPQAAgjAqgpQAngrAiAAQAUAAAAASQAAAMgIAPQgIARgLgBIgGgDIgCgFQAAgJAPgJQAPgKAAgKQAAgNgNAAQgXAAgmA2QgmAzAAAaQAAAIAGAGQAHAGAJAAQAWAAAegdIArguIAGAAQgfAkgQAOQgeAdgdAAQgOAAgKgMg");
	this.shape_17.setTransform(36.5,-27.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FF0000").s().p("AgIAlIgZAbQgPAPgQAAQgLAAgHgMQgFgKAAgNQAAgWALgSQAPgXAhgcQAlgfAXAAQAQAAgEAXIANgSIAYAAIgvBGQggAyAAATQAAAKALAAQASAAAYgeQARgXAMgXIAEAAQgmBPgnAAQgTAAAAgqgAgggTQgpA2AAAbQAAAOAKAAQAWAAApg8QApg4AAgYQAAgMgJAAQgZAAgnA5g");
	this.shape_18.setTransform(22.1,-27.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FF0000").s().p("AieDGIEFmLIAMAAIhOCAQAog1AagBQAJAAAGAHQAGAIAAAIQAAAWghArQgiAqAAAQQAAAJAKAAQAdAAA6hMIAFAAQg+BPgfAAQgKAAgGgIQgGgJAAgKQAAgWARgYQAFgHAcggQASgSAAgMQAAgLgKAAQgfAAgqBCIigD6g");
	this.shape_19.setTransform(-0.4,-22.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FF0000").s().p("AgDBJQgGgIAAgJQAAgLAJgRQAIgRAAgIQAAgDgDgDQgLAAgHgFIg4BTIgYAAIBiiaIAZAAIgXAjIAcgVQATgMANAAQAVAAAAAQQAAAFgDADIgGAGQgCACgDgBQgCAAAAgEQAEgIAAgHQAAgIgJAAQgRAAgbAWQgVATgMASQAPAHAFAEQAHALAAAJQAAALgIAQQgJARAAAIQAAAIAKAAQAPAAAdggQAFgGAggnIADAAQg6BQgZAAQgJAAgFgHg");
	this.shape_20.setTransform(-9.1,-27.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FF0000").s().p("AgtBrQABgRAEgPQgTAbgIAHQgUAWgQAAQgSAAAAgeQAAgZAZgoIApg6IAYAAIguBEQghAzAAASQAAAMAMAAQASAAAuhBQAPgVAng/IAXAAIgtBEQggAzAAAUQAAAKAMAAQAQAAAZggQAUgXAMgXIAFAAQgyBSggAAQgSAAgBgYgAArhaQANgGAKABQAJAAAHgCQAOgHAYgZIACgBQgbAmgaAMQgIAEgLgBQgKAAgHADQgQAIgTAXIgEABQAggpARgHg");
	this.shape_21.setTransform(-29.2,-32.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FF0000").s().p("AhrBEQgHgIAAgJQAAgaAZgnIANgUIAegrIAYAAIgvBGQghAxAAAVQAAAJAMAAQAYgBAagiIAFgGIgGgCQgLgFgFgIQgEgIADgIQACgKAKgIQAPgDAJAGQAJAFADAKQADAJgDAOIgCADIACgBQALgCALgJQAIgGAIgIIAIgOIAOgUIAegrIAYAAIgvBGQghAxAAAUQAAAKAMAAQAPAAAbgfIASgXIAPgVIAEAAQgyBPghAAQgJAAgGgIQgFgIAAgJQAAgRAKgXIgJAHQgNAKgLACIgDABQgEAJgIAHQgOANgQAJQgRAIgNABQgOgCgHgIgAgrgOQgLAIgBAHQgBAKAGAHQAFAHALADIABAAIAFgLQADgLAAgHQAAgIgEgEQgCgDgEAAQgEAAgEACg");
	this.shape_22.setTransform(-50.7,-27);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FF0000").s().p("AArBEQgEgIABgLQABgMADgMQADgLADgGQAGgLAMgQQANgRARgcQgEgDgHAFQgGAFgJAJIgSAVIgSAYIgPASIgJAPIgIALIgJAPIgLANQgFAGgDAAQgGAAgDgCQgCgCgBgDQgBgEABgEIAAgIQABgMAGgQQAHgQAJgOIARggIASgbQgJABgNAOQgNAOgQASIggAmIgaAiQgNAQgIAEQgIADgIAAQgJgBgFgLQgFgLABgPQAAgOAFgRQAFgNAMgKQALgEADADQADAFgBADQgNAJgHALQgIALgCAKQgDAKABAJQAAAIADAGQAHANANgHQAIgEAIgJIATgXIAUgcIAWgaQAUgYAPgNQANgNAPgGIAUAAIgXAmIgYAoIgRAjQgHAQgBAIQAAAFAEAAIAIgIIANgUIATgaIAUgaIALgPIAPgSQAJgKAJgHQAKgIAKgEQAIgCAGAAIAMABIgXAjIgYAjQggAwAAAVQAAAKALAAQAQAAAbggIATgXQAKgMAGgJIAFAAQgZAngXAUQgWAVgQgBQgMABgDgKg");
	this.shape_23.setTransform(-74.3,-27.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FF0000").s().p("AgIAlIgZAbQgPAPgQAAQgLAAgHgMQgFgKAAgNQAAgWALgSQAPgXAhgcQAlgfAXAAQAQAAgEAXIANgSIAYAAIgvBGQggAyAAATQAAAKALAAQASAAAYgeQARgXAMgXIAEAAQgmBPgnAAQgTAAAAgqgAgggTQgpA2AAAbQAAAOAKAAQAWAAApg8QApg4AAgYQAAgMgJAAQgZAAgnA5g");
	this.shape_24.setTransform(-96,-27.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FF0000").s().p("Ah+CvQgSgZAAgpQAAgpAWgwQhlgXAAg7QAAgvAxgYQAngTA1AAQA8AAAkAUQBfhJBBAAQAWAAAOAMQAOAMAAAWQAABDhJBOQhJBMhDAAQgOAAgKgPQgIgNABgQQgnAIgXgBQgoBLAAA0QAAAYAPANQAQANAZAAQAoAABEgxQA1glAsgsIADACQgtAug1AkQhFAygqAAQgnAAgUgfgACeh+QAAAshDAvQg5AngyANIAAAHQAAANAHAKQAHALALAAQAkAAA0gpQAxgkAkg0QAmg2AAgkQAAgpguAAQgfAAgsAeQgjAWgeAeIATAPIgBABIgUgOQg8Ayg0BaQANAAAwgGQAMgzAugzQA1g3AzAAQAPAAAAAPgAioiBQgzAWAAAxQAAAdAkAXQAaAOAlAKQAWgnAkgqQAlgpAkgZQghgSg1AAQg4AAglASgAAqhUQgvAzgLAwQA0gPA1glQBDgvAAgqQAAgNgOAAQgvAAg1A3g");
	this.shape_25.setTransform(-114.3,-37.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-187.9,-71.2,376,142.5);


(lib.heart = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.flash01();
	this.instance.setTransform(-12.5,-9.8,0.03,0.03);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-12.5,-9.8,25.1,19.8);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Persivald();
	this.instance.setTransform(-250,-250);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-250,-250,500,500);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FF00").s().p("AgxA7QgVgSAAgbQAAggAUgbQAXgeAgAAQBCAAAAA+QAAAfgSAaQgWAgggAAQgcAAgUgRgAgcgcQgOAUAAAWQAAAPAMALQALAJASAAQASAAAOgUQAMgUAAgWQAAgUgIgHQgJgJgVABQgSAAgPAUg");
	this.shape.setTransform(31.1,132.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00FF00").s().p("AgsA5QgVgRAAgeQAAggARgXQASgaAeAAQAVAAAOAIQARAIAAAUQAAANgPALQgHAEgVAIIgxAZQAHALAMAGQALAFAMAAQAKAAAMgDQAQgFAEgHQAFgHAFAAQAFAAADADQAEAEAAAEQAAAPgYALQgUAJgUAAQgcAAgSgPgAgagjQgLANgFAXIApgRQAWgMAKgIQgMgLgTAAQgPAAgLAMg");
	this.shape_1.setTransform(15.8,132.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#00FF00").s().p("AhKBEIAAgPIABgPQgBgHAFgDQAFgEAFABQAOgTAFgXQAEgRAAgeQgBgMAGgFQAFgFANAAIANAAIAMABIAPgBIAOgBQALAAADAJQABAFAAANIgBASIAAASIAAAZIAAAbQAUAAgBANIAAAQIABARQAAAFgEAEQgEAEgFAAQgOAAAAgWIAAgHIAAgFIhIAAIgLABIgNAAIAAAKIABAKQAAAGgEAEQgEAEgGAAQgNAAAAgUgAggAbIAIgBIA1AAIgBgaIAAgYIABgSIABgRIgoAAQAAAwgWAmg");
	this.shape_2.setTransform(-0.1,134.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00FF00").s().p("AAtBGQgDgEAAgGIAAgaIABgZQAAgPgCgPIgYAgQgOASgMAMIgbAYQgHAIgHAAQgGAAgFgEQgEgDAAgGIgChNIgBgpQAAgOANAAQAMAAABANIABAaIACBAQAUgSAUgZIAlgwQAIgLAJAAQAFAAAEAEQAEAEAAAFIABAtIAAAqIAAAQIgBAPQAAAGgEAEQgEADgFAAQgGAAgEgDg");
	this.shape_3.setTransform(-17.2,132.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#00FF00").s().p("AgxBEQgFgEAAgFIAAgZIAChGIAAgNQAAgIACgFQABgEACgBIAIgCQAIgCASAAQAUAAARAKQAVAMAAAUQAAATgVAJQALACAJAKQALALAAAJQAAAZgnAKQgVAGgiAAQgFAAgFgEgAgdAXIAAAaQA5gCAAgRQAAgHgKgGQgJgFgIgCIgOgBIgPgBIgBAPgAgbgwIgBAPIABAKIAAAKIAOABQANAAAHgCQANgEAAgLQAAgIgLgGQgJgFgIAAIgFAAIgOAAg");
	this.shape_4.setTransform(-31.9,132.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#00FF00").s().p("AgUBGIgNAAIgFAAQgNAAAAgSIABgQQACgSAAgPIgBgdIgBgeQAAgOANAAQANAAAAAMIACAnIAKAAQAeAAAPAIQATALAAAaQAAAXgSAMQgQAKgZAAIgNgBgAgWACIAAAFIgCAoIARABQAhAAAAgWQAAgPgJgFQgHgFgRAAIgPABg");
	this.shape_5.setTransform(69.8,88.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#00FF00").s().p("AgHBHQgEgEAAgFIABgQIAAgOIgDhNIgRgBQgLAAgFgBQgIgEgBgJQABgFADgEQADgEAGAAIBNAAQAKAAAEACQAHADgBAIQAAAHgDADQgEAEgGAAIgKAAIgLAAIgJAAIACBdQAAAbgOAAQgDAAgEgDg");
	this.shape_6.setTransform(56.5,88.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#00FF00").s().p("AgsA5QgVgRAAgdQAAghARgYQASgZAeAAQAVAAAOAHQARAKAAASQAAAOgPALQgHAEgVAJIgxAYQAHALAMAFQALAGAMAAQAKAAAMgEQAQgEAEgHQAFgHAFAAQAFAAADAEQAEADAAAFQAAAOgYALQgUAJgUAAQgcAAgSgPgAgagjQgLANgFAYIApgSQAWgMAKgJQgMgKgTAAQgPAAgLAMg");
	this.shape_7.setTransform(42.8,88.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#00FF00").s().p("AgzBrQgDgDAAgGIAAg1IAAg0IgBg1IgCgbQAAgJADgHQAEgHAHAAQAFAAAEAEQAEADAAAGIgBADIgBAIQAMgHALgEQAJgEAJAAQAbAAANAYQAJATABAgQAAAagQATQgQATgbAAQgMAAgPgDIgBA/QAAAGgEADQgEAEgFAAQgGAAgEgEgAgLhGQgIAEgKALQABAeABAgQAOAFANAAQAQAAAJgMQAIgKAAgQQgBgYgFgMQgGgNgMAAQgLAAgJAFg");
	this.shape_8.setTransform(28,91.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#00FF00").s().p("AgHBHQgEgEAAgFIAAgQIAAgOIgChNIgRgBQgMAAgEgBQgJgEAAgJQAAgFAEgEQAEgEAGAAIBMAAQAKAAAEACQAGADABAIQgBAHgDADQgDAEgHAAIgKAAIgLAAIgJAAIACBdQAAAbgOAAQgDAAgEgDg");
	this.shape_9.setTransform(14.1,88.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#00FF00").s().p("AgxA7QgVgRAAgdQAAgeAUgbQAXgfAgAAQBCAAAAA+QAAAfgSAbQgWAfggAAQgcAAgUgRgAgcgbQgOATAAAVQAAARAMAJQALAKASAAQASAAAOgVQAMgTAAgWQAAgUgIgIQgJgHgVgBQgSAAgPAWg");
	this.shape_10.setTransform(-0.4,88.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#00FF00").s().p("AA/A2IgEgQQgGgQgJgsIgWAzIgHARQgEALgEAGQgFAIgHAAQgHAAgEgHIgIgTQgLgfgJgjIgDAPIgPAtQgBAJgFARQgDAHgIAAQgNABAAgLQAAgPAIgXIANgiIAGgeQAFgUAGgGQAFgGAHABQAIgBADAIQAFAHAFAaQAGAdAMAgQAPghAMglIAGgVQAFgMALAAQANAAAFAbIACAKQAGAnALAeIAKAfQAAAFgEADQgEACgFAAQgMAAgFgUg");
	this.shape_11.setTransform(-18.6,88.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#00FF00").s().p("AglA6QgTgSAAgcQAAgZASgcQAUghAXAAQANAAAQAHQAUAIAAALQABAFgEAEQgDAEgFgBQgEAAgDgCIgFgEQgIgGgSAAQgMAAgNAYQgMAWAAAOQAAASAMAKQALAJAPAAQAJAAAJgEIAPgIQAEgDACAAQAFAAADAFQAEADAAAGQAAAKgVAJQgRAHgNABQgYAAgTgRg");
	this.shape_12.setTransform(-35.3,88.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#00FF00").s().p("AgxA7QgVgRAAgdQAAgeAUgbQAXgfAgAAQBCAAAAA+QAAAfgSAbQgWAfggAAQgcAAgUgRgAgcgbQgOATAAAVQAAARAMAJQALAKASAAQASAAAOgVQAMgTAAgWQAAgUgIgIQgJgHgVgBQgSAAgPAWg");
	this.shape_13.setTransform(-50.5,88.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#00FF00").s().p("Ag7BEQgEgDAAgGIACgTIABgUIgCgiIgBglQAAgIAEgEQAFgFAHAAIAOgCIAPgBIAhAAIAiABQAGAAAEAEQADADAAAGIgBAaIAAAaIACAeIABAhQABAGgEADQgEAEgGAAQgFAAgEgEQgEgDAAgGIgCggIgCgeIABgoIgbAAIgagBIgTACIACAhIABAeIgBAUIgBATQAAAGgDADQgFAEgGAAQgFAAgEgEg");
	this.shape_14.setTransform(-66.9,88.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#00FF00").s().p("AgUBGIgNAAIgFAAQgNAAAAgSIABgQQACgSAAgPIgBgdIgBgeQAAgOANAAQANAAAAAMIACAnIAKAAQAeAAAPAIQATALAAAaQAAAXgSAMQgQAKgZAAIgNgBgAgWACIAAAFIgCAoIARABQAhAAAAgWQAAgPgJgFQgHgFgRAAIgPABg");
	this.shape_15.setTransform(41.6,44.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#00FF00").s().p("AgFBKIhHgBQgGAAgEgEQgEgEAAgGIADgdQADgeAAg9QAAgFAEgEQADgEAGAAQAFAAAEAEQAEAEAAAFQAABEgEAoIAWABIANgBIANAAIABAAQACgLAAgPIgBgcIgBgdQAAgkAOAAQAFAAAFAEQAEAEAAAFIgCALIgBANIAAAcIABAaIgBANIAAAOIAAABIAWABIANgBIANAAIABAAQACgLAAgPIgBgcIgBgdQAAgkAQAAQAFAAAFAEQAEAEAAAFIgCALIgBANIAAAcIABAaIgBANIAAAOQAAAQgEAGQgFAHgQAAIhEgBg");
	this.shape_16.setTransform(24.1,44.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#00FF00").s().p("AgsA5QgVgQAAgfQAAggARgXQASgaAeAAQAVAAAOAIQARAIAAAUQAAANgPALQgHAEgVAIIgxAZQAHALAMAGQALAFAMAAQAKAAAMgDQAQgFAEgHQAFgHAFAAQAFAAADADQAEAEAAAEQAAAQgYAKQgUAJgUAAQgcAAgSgPgAgagiQgLAMgFAXIApgRQAWgMAKgIQgMgLgTAAQgPAAgLANg");
	this.shape_17.setTransform(6.4,44.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#00FF00").s().p("AAlBIQgEgEAAgGIgBguQgQAMgVAAQgdAAgNgTQgMgSAAgsQAAgVAOAAQAGAAAEADQADAEAAAGIAAAFIAAADQAAAkAGALQAHAKARAAQAHgBALgDQAMgHAEgHIAAgQIABgQIgBgIIAAgIQAAgGAEgDQAEgEAGABQANAAAAAXIAAAKIAAAIIAAAvIABAwQAAAGgEAEQgEAEgFAAQgGAAgEgEg");
	this.shape_18.setTransform(-8.8,44.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#00FF00").s().p("AgxA7QgVgRAAgcQAAggAUgbQAXgeAgAAQBCAAAAA+QAAAfgSAaQgWAgggAAQgcAAgUgRgAgcgcQgOAUAAAWQAAAPAMALQALAJASAAQASAAAOgVQAMgSAAgXQAAgUgIgHQgJgIgVAAQgSgBgPAVg");
	this.shape_19.setTransform(-23.9,44.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#00FF00").s().p("AApBHIgpg3IgaAbIgXAWQgEAFgFgBQgFAAgEgDQgEgFAAgEQAAgFADgEQAEgFAIgHIAMgLIAcgcIgRgZQgLgPgIgHQgFgEAAgFQAAgGAEgEQAEgEAFgBQAIAAAQAVIAVAgIAagYQAQgPAGgJQAEgGAGAAQAFAAAEADQAEAFAAAEQAAAIgMANIgUASIgYAXIAsA4QADADAAAEQAAAGgEAEQgEAEgFAAQgFAAgEgFg");
	this.shape_20.setTransform(-40,44.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#00FF00").s().p("AAtBGQgDgEAAgGIAAgaIABgZQAAgPgCgPIgYAgQgOASgMAMIgbAYQgHAIgHAAQgGAAgFgEQgEgDAAgGIgChNIgBgpQAAgOANAAQAMAAABANIABAaIACBAQAUgSAUgZIAlgwQAIgLAJAAQAFAAAEAEQAEAEAAAFIABAtIAAAqIAAAQIgBAPQAAAGgEAEQgEADgFAAQgGAAgEgDg");
	this.shape_21.setTransform(65.1,0.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#00FF00").s().p("AA1BFQgDgEAAgFIgBgMIgBgMIAAgcIAAgzQgIABgJAAIgqgBIABARIAAARQAAAogFAPQgIAagaAAQgKAAgHgEQgJgFAAgJQAAgFADgEQADgDAFAAIAIACIAHACQAKAAADgOQABgIAAgUIgBgeIgBgfQAAgGAEgDQAEgEAGAAIAJABIAJAAIAkABIAOgCIAPgCQAPAAAAANIAAAiIgBAhIABAbIAAANIABAMQAAAFgDAEQgEAEgGAAQgGAAgEgEg");
	this.shape_22.setTransform(47.3,0.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#00FF00").s().p("AglA6QgTgSAAgcQAAgZASgdQAUgfAXgBQANABAQAFQAUAJABALQAAAFgEAEQgDAEgFAAQgEAAgDgDIgFgEQgIgGgSgBQgLAAgOAZQgMAWAAAOQAAASAMAKQALAJAPAAQAIABAJgFIAQgIQAEgCACAAQAFAAADADQAEAEAAAFQAAALgUAIQgTAJgMgBQgZAAgSgQg");
	this.shape_23.setTransform(32.4,0.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#00FF00").s().p("AgsA5QgVgRAAgdQAAghARgXQASgaAeAAQAVAAAOAIQARAIAAAUQAAANgPALQgHAEgVAIIgxAZQAHALAMAGQALAFAMAAQAKAAAMgDQAQgFAEgHQAFgHAFAAQAFAAADADQAEAEAAAEQAAAQgYAKQgUAJgUAAQgcAAgSgPgAgagiQgLAMgFAXIApgRQAWgMAKgIQgMgLgTAAQgPAAgLANg");
	this.shape_24.setTransform(18,0.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#00FF00").s().p("AAGgdIATgCIgmA9IgMACg");
	this.shape_25.setTransform(-2,5.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#00FF00").s().p("AAqBDQgGgFgDgEQgNAGgKAEQgKADgEAAQgfAAgPgRQgMgRAAghQgBgfAWgWQAXgYAcAAQAMAAAPAHQARAHABALQgBADgCADQgBAFgBALIgBAcQAAAQACALIAIAWIAEAIIABACQAAAGgFADQgDAEgFAAQgDgBgGgGgAgWggQgOAQAAAUQgBAXAIALQAIAKAPABQALAAAJgGQAFgCAJgIQgEghgBgSIABgMIACgOIgIgEIgGgBQgTAAgPARg");
	this.shape_26.setTransform(-12.3,0.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#00FF00").s().p("AhKBEIAAgPIAAgPQABgHAEgDQAEgEAHABQAOgTAEgXQADgRAAgeQABgMAFgFQAGgFAMAAIAMAAIANABIAPgBIAOgBQAKAAADAJQACAFAAANIAAASIgBASIAAAZIABAbQATAAAAANIAAAQIAAARQAAAFgEAEQgDAEgHAAQgNAAAAgWIAAgHIAAgFIhIAAIgMABIgLAAIAAAKIAAAKQAAAGgEAEQgDAEgHAAQgNAAAAgUgAgfAbIAHgBIA1AAIAAgaIAAgYIAAgSIABgRIgoAAQAAAwgVAmg");
	this.shape_27.setTransform(-27.6,1.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#00FF00").s().p("AgIA9QgVgRAAgcIAAgCIgFAAQgNAAgMABIgaAFIgBAtQAAAGgEADQgEADgEAAQgMgBAAgLQAAgZACgbIAEgzIABgNIABgOQAAgMAMAAQAMAAAAAMIgBAPIgBAOIgDAhQAlgFAMgBIAJAAQAIgbARgRQATgUAbAAQBBAAAAA+QAAAfgSAbQgVAfgjAAQgcAAgRgRgAAKgaQgMAUAAAWQAAARAKAKQAMAJARAAQAVAAAOgUQANgUAAgXQAAgUgJgIQgJgIgVAAQgVAAgPAVg");
	this.shape_28.setTransform(-47.9,-0.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#00FF00").s().p("AglA6QgTgSAAgcQAAgZASgdQAUgfAXgBQANABAQAFQAVAJgBALQAAAFgDAEQgDAEgFAAQgEAAgDgDIgGgEQgHgGgSgBQgMAAgNAZQgMAWAAAOQAAASAMAKQALAJAQAAQAHABAKgFIAPgIQAEgCACAAQAFAAADADQAEAEAAAFQAAALgVAIQgRAJgMgBQgZAAgTgQg");
	this.shape_29.setTransform(-67,0.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#00FF00").s().p("AAtBqQgDgFAAgFIAAgaIABgZQAAgRgCgPIgYAhQgOATgMALIgbAZQgHAHgHABQgGgBgFgDQgEgDAAgGIgChPIgBgoQAAgNANAAQAMAAABAMIABAZIACBCQAUgSAUgbIAlguQAIgLAJAAQAFAAAEADQAEAEAAAGIABAqIAAAtIAAAQIgBAPQAAAFgEAFQgEADgFAAQgGAAgEgDgAgkhDQgOgMAAgTQAAgKAKAAQAKAAAAAKQAAAKAJAIQAIAGALAAQAlAAAFgVQADgIAHAAQAEAAADACQADAEAAADIAAACQgCAVgWAKQgRAIgVAAQgTAAgPgOg");
	this.shape_30.setTransform(42,-47.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#00FF00").s().p("AAqBDQgGgFgDgFQgNAIgJADQgKADgFABQgfAAgOgSQgNgQgBgjQAAgdAXgYQAVgWAeAAQALAAAOAFQATAIgBAKQAAAEgCADQgBAFgBAMIgBAbQgBAQADAKIAIAYIADAHIABACQAAAGgEADQgDADgFAAQgDABgGgHgAgVggQgPARgBATQABAWAHALQAIALAQAAQAKAAAJgEQAFgDAIgHQgEgiAAgRIABgNIACgOIgIgEIgGgBQgSAAgPARg");
	this.shape_31.setTransform(26.9,-43.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#00FF00").s().p("AgyBEQgEgDAAgFIABgUIAAgTIgBgkIAAgnQgBgRAOAAQAGAAAEAEQADADABAGIABAnIAJAAQARgBAFgOIAFgNQALgVAPAAQAEAAAGACQAGADAAAFQABAKgJAAQgIABgIARIgGAOQgFAHgEAFQANAHAPAWQAOAWAAALQAAAFgDAEQgFAEgFgBQgJAAgEgJQgEgJgQgXQgOgYgFAAIgQAAIAAAQIAAAQIgBAYQgCALgLAAQgFAAgFgEg");
	this.shape_32.setTransform(13.6,-44.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#00FF00").s().p("AAqBDQgGgFgDgFQgNAIgKADQgKADgEABQgfAAgPgSQgNgQABgjQAAgdAVgYQAXgWAcAAQAMAAAOAFQASAIAAAKQAAAEgCADQgCAFAAAMIgBAbQAAAQACAKIAJAYIADAHIAAACQAAAGgDADQgEADgFAAQgCABgHgHgAgWggQgOARAAATQgBAWAIALQAIALAPAAQALAAAJgEQAFgDAJgHQgEgiAAgRIAAgNIACgOIgIgEIgGgBQgTAAgPARg");
	this.shape_33.setTransform(-0.5,-43.7);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#00FF00").s().p("AA/A2IgEgQQgGgQgJgsIgWAzIgHASQgEAKgEAHQgFAGgHABQgHgBgEgFIgIgUQgLgfgJgjIgDAPIgPAtQgBAKgFAQQgDAIgIAAQgNAAAAgLQAAgPAIgXIANgjIAGgdQAFgUAGgGQAFgGAHABQAIAAADAGQAFAJAFAZQAGAdAMAgQAPghAMglIAGgVQAFgMALAAQANAAAFAaIACALQAGAnALAdIAKAgQAAAEgEAEQgEACgFAAQgMAAgFgUg");
	this.shape_34.setTransform(-17.7,-43.9);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#00FF00").s().p("AgNBaIABgeIABgdIAAgfIgKAAQgKAAgZAoQgXAkgGAQQgDALgJAAQgGgBgEgDQgEgEAAgFQAAgTAZglQAYgkARgIQgRgKgKgaQgNgfgOAAQgHAAAAgLQAAgEAGgDQAGgDAFAAQAWAAANAgIAFAPQAEAMAHAFQAKAIAQAAIgCg3QAAgVAOAAQADAAAEAEQAEAEAAAFIABBAQAQAAAKgHQAHgHAEgLIAGgQQAOggAVAAQAFAAAGADQAHACAAAFQAAALgHAAQgPAAgMAfQgLAagRAKQARAIAYAkQAZAlAAATQAAAFgEAEQgEADgGABQgJAAgDgLQgGgQgWgkQgagogKAAIgJAAIgBAbIAAAcQAAAggBAEQgCAMgJAAQgNAAAAgNg");
	this.shape_35.setTransform(-39.5,-47.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFF00").s().p("AgxA7QgVgSAAgbQAAggAUgbQAXgeAgAAQBCAAAAA+QAAAfgSAaQgWAgggAAQgcAAgUgRgAgcgcQgOAUAAAWQAAAPAMALQALAJASAAQASAAAOgUQAMgUAAgWQAAgUgIgHQgJgJgVABQgSAAgPAUg");
	this.shape_36.setTransform(31.1,132.6);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFF00").s().p("AgsA5QgVgRAAgeQAAggARgXQASgaAeAAQAVAAAOAIQARAIAAAUQAAANgPALQgHAEgVAIIgxAZQAHALAMAGQALAFAMAAQAKAAAMgDQAQgFAEgHQAFgHAFAAQAFAAADADQAEAEAAAEQAAAPgYALQgUAJgUAAQgcAAgSgPgAgagjQgLANgFAXIApgRQAWgMAKgIQgMgLgTAAQgPAAgLAMg");
	this.shape_37.setTransform(15.8,132.8);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFF00").s().p("AhKBEIAAgPIABgPQgBgHAFgDQAFgEAFABQAOgTAFgXQAEgRAAgeQgBgMAGgFQAFgFANAAIANAAIAMABIAPgBIAOgBQALAAADAJQABAFAAANIgBASIAAASIAAAZIAAAbQAUAAgBANIAAAQIABARQAAAFgEAEQgEAEgFAAQgOAAAAgWIAAgHIAAgFIhIAAIgLABIgNAAIAAAKIABAKQAAAGgEAEQgEAEgGAAQgNAAAAgUgAggAbIAIgBIA1AAIgBgaIAAgYIABgSIABgRIgoAAQAAAwgWAmg");
	this.shape_38.setTransform(-0.1,134.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFF00").s().p("AAtBGQgDgEAAgGIAAgaIABgZQAAgPgCgPIgYAgQgOASgMAMIgbAYQgHAIgHAAQgGAAgFgEQgEgDAAgGIgChNIgBgpQAAgOANAAQAMAAABANIABAaIACBAQAUgSAUgZIAlgwQAIgLAJAAQAFAAAEAEQAEAEAAAFIABAtIAAAqIAAAQIgBAPQAAAGgEAEQgEADgFAAQgGAAgEgDg");
	this.shape_39.setTransform(-17.2,132.8);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFF00").s().p("AgxBEQgFgEAAgFIAAgZIAChGIAAgNQAAgIACgFQABgEACgBIAIgCQAIgCASAAQAUAAARAKQAVAMAAAUQAAATgVAJQALACAJAKQALALAAAJQAAAZgnAKQgVAGgiAAQgFAAgFgEgAgdAXIAAAaQA5gCAAgRQAAgHgKgGQgJgFgIgCIgOgBIgPgBIgBAPgAgbgwIgBAPIABAKIAAAKIAOABQANAAAHgCQANgEAAgLQAAgIgLgGQgJgFgIAAIgFAAIgOAAg");
	this.shape_40.setTransform(-31.9,132.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFF00").s().p("AgUBGIgNAAIgFAAQgNAAAAgSIABgQQACgSAAgPIgBgdIgBgeQAAgOANAAQANAAAAAMIACAnIAKAAQAeAAAPAIQATALAAAaQAAAXgSAMQgQAKgZAAIgNgBgAgWACIAAAFIgCAoIARABQAhAAAAgWQAAgPgJgFQgHgFgRAAIgPABg");
	this.shape_41.setTransform(69.8,88.3);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFF00").s().p("AgHBHQgEgEAAgFIABgQIAAgOIgDhNIgRgBQgLAAgFgBQgIgEgBgJQABgFADgEQADgEAGAAIBNAAQAKAAAEACQAHADgBAIQAAAHgDADQgEAEgGAAIgKAAIgLAAIgJAAIACBdQAAAbgOAAQgDAAgEgDg");
	this.shape_42.setTransform(56.5,88.7);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFF00").s().p("AgsA5QgVgRAAgdQAAghARgYQASgZAeAAQAVAAAOAHQARAKAAASQAAAOgPALQgHAEgVAJIgxAYQAHALAMAFQALAGAMAAQAKAAAMgEQAQgEAEgHQAFgHAFAAQAFAAADAEQAEADAAAFQAAAOgYALQgUAJgUAAQgcAAgSgPgAgagjQgLANgFAYIApgSQAWgMAKgJQgMgKgTAAQgPAAgLAMg");
	this.shape_43.setTransform(42.8,88.6);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFF00").s().p("AgzBrQgDgDAAgGIAAg1IAAg0IgBg1IgCgbQAAgJADgHQAEgHAHAAQAFAAAEAEQAEADAAAGIgBADIgBAIQAMgHALgEQAJgEAJAAQAbAAANAYQAJATABAgQAAAagQATQgQATgbAAQgMAAgPgDIgBA/QAAAGgEADQgEAEgFAAQgGAAgEgEgAgLhGQgIAEgKALQABAeABAgQAOAFANAAQAQAAAJgMQAIgKAAgQQgBgYgFgMQgGgNgMAAQgLAAgJAFg");
	this.shape_44.setTransform(28,91.8);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFF00").s().p("AgHBHQgEgEAAgFIAAgQIAAgOIgChNIgRgBQgMAAgEgBQgJgEAAgJQAAgFAEgEQAEgEAGAAIBMAAQAKAAAEACQAGADABAIQgBAHgDADQgDAEgHAAIgKAAIgLAAIgJAAIACBdQAAAbgOAAQgDAAgEgDg");
	this.shape_45.setTransform(14.1,88.7);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFF00").s().p("AgxA7QgVgRAAgdQAAgeAUgbQAXgfAgAAQBCAAAAA+QAAAfgSAbQgWAfggAAQgcAAgUgRgAgcgbQgOATAAAVQAAARAMAJQALAKASAAQASAAAOgVQAMgTAAgWQAAgUgIgIQgJgHgVgBQgSAAgPAWg");
	this.shape_46.setTransform(-0.4,88.5);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFF00").s().p("AA/A2IgEgQQgGgQgJgsIgWAzIgHARQgEALgEAGQgFAIgHAAQgHAAgEgHIgIgTQgLgfgJgjIgDAPIgPAtQgBAJgFARQgDAHgIAAQgNABAAgLQAAgPAIgXIANgiIAGgeQAFgUAGgGQAFgGAHABQAIgBADAIQAFAHAFAaQAGAdAMAgQAPghAMglIAGgVQAFgMALAAQANAAAFAbIACAKQAGAnALAeIAKAfQAAAFgEADQgEACgFAAQgMAAgFgUg");
	this.shape_47.setTransform(-18.6,88.6);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFF00").s().p("AglA6QgTgSAAgcQAAgZASgcQAUghAXAAQANAAAQAHQAUAIAAALQABAFgEAEQgDAEgFgBQgEAAgDgCIgFgEQgIgGgSAAQgMAAgNAYQgMAWAAAOQAAASAMAKQALAJAPAAQAJAAAJgEIAPgIQAEgDACAAQAFAAADAFQAEADAAAGQAAAKgVAJQgRAHgNABQgYAAgTgRg");
	this.shape_48.setTransform(-35.3,88.6);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFF00").s().p("AgxA7QgVgRAAgdQAAgeAUgbQAXgfAgAAQBCAAAAA+QAAAfgSAbQgWAfggAAQgcAAgUgRgAgcgbQgOATAAAVQAAARAMAJQALAKASAAQASAAAOgVQAMgTAAgWQAAgUgIgIQgJgHgVgBQgSAAgPAWg");
	this.shape_49.setTransform(-50.5,88.5);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFF00").s().p("Ag7BEQgEgDAAgGIACgTIABgUIgCgiIgBglQAAgIAEgEQAFgFAHAAIAOgCIAPgBIAhAAIAiABQAGAAAEAEQADADAAAGIgBAaIAAAaIACAeIABAhQABAGgEADQgEAEgGAAQgFAAgEgEQgEgDAAgGIgCggIgCgeIABgoIgbAAIgagBIgTACIACAhIABAeIgBAUIgBATQAAAGgDADQgFAEgGAAQgFAAgEgEg");
	this.shape_50.setTransform(-66.9,88.6);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFF00").s().p("AgUBGIgNAAIgFAAQgNAAAAgSIABgQQACgSAAgPIgBgdIgBgeQAAgOANAAQANAAAAAMIACAnIAKAAQAeAAAPAIQATALAAAaQAAAXgSAMQgQAKgZAAIgNgBgAgWACIAAAFIgCAoIARABQAhAAAAgWQAAgPgJgFQgHgFgRAAIgPABg");
	this.shape_51.setTransform(41.6,44.2);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFF00").s().p("AgFBKIhHgBQgGAAgEgEQgEgEAAgGIADgdQADgeAAg9QAAgFAEgEQADgEAGAAQAFAAAEAEQAEAEAAAFQAABEgEAoIAWABIANgBIANAAIABAAQACgLAAgPIgBgcIgBgdQAAgkAOAAQAFAAAFAEQAEAEAAAFIgCALIgBANIAAAcIABAaIgBANIAAAOIAAABIAWABIANgBIANAAIABAAQACgLAAgPIgBgcIgBgdQAAgkAQAAQAFAAAFAEQAEAEAAAFIgCALIgBANIAAAcIABAaIgBANIAAAOQAAAQgEAGQgFAHgQAAIhEgBg");
	this.shape_52.setTransform(24.1,44.2);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFF00").s().p("AgsA5QgVgQAAgfQAAggARgXQASgaAeAAQAVAAAOAIQARAIAAAUQAAANgPALQgHAEgVAIIgxAZQAHALAMAGQALAFAMAAQAKAAAMgDQAQgFAEgHQAFgHAFAAQAFAAADADQAEAEAAAEQAAAQgYAKQgUAJgUAAQgcAAgSgPgAgagiQgLAMgFAXIApgRQAWgMAKgIQgMgLgTAAQgPAAgLANg");
	this.shape_53.setTransform(6.4,44.5);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFF00").s().p("AAlBIQgEgEAAgGIgBguQgQAMgVAAQgdAAgNgTQgMgSAAgsQAAgVAOAAQAGAAAEADQADAEAAAGIAAAFIAAADQAAAkAGALQAHAKARAAQAHgBALgDQAMgHAEgHIAAgQIABgQIgBgIIAAgIQAAgGAEgDQAEgEAGABQANAAAAAXIAAAKIAAAIIAAAvIABAwQAAAGgEAEQgEAEgFAAQgGAAgEgEg");
	this.shape_54.setTransform(-8.8,44.2);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFF00").s().p("AgxA7QgVgRAAgcQAAggAUgbQAXgeAgAAQBCAAAAA+QAAAfgSAaQgWAgggAAQgcAAgUgRgAgcgcQgOAUAAAWQAAAPAMALQALAJASAAQASAAAOgVQAMgSAAgXQAAgUgIgHQgJgIgVAAQgSgBgPAVg");
	this.shape_55.setTransform(-23.9,44.3);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFF00").s().p("AApBHIgpg3IgaAbIgXAWQgEAFgFgBQgFAAgEgDQgEgFAAgEQAAgFADgEQAEgFAIgHIAMgLIAcgcIgRgZQgLgPgIgHQgFgEAAgFQAAgGAEgEQAEgEAFgBQAIAAAQAVIAVAgIAagYQAQgPAGgJQAEgGAGAAQAFAAAEADQAEAFAAAEQAAAIgMANIgUASIgYAXIAsA4QADADAAAEQAAAGgEAEQgEAEgFAAQgFAAgEgFg");
	this.shape_56.setTransform(-40,44.1);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFF00").s().p("AAtBGQgDgEAAgGIAAgaIABgZQAAgPgCgPIgYAgQgOASgMAMIgbAYQgHAIgHAAQgGAAgFgEQgEgDAAgGIgChNIgBgpQAAgOANAAQAMAAABANIABAaIACBAQAUgSAUgZIAlgwQAIgLAJAAQAFAAAEAEQAEAEAAAFIABAtIAAAqIAAAQIgBAPQAAAGgEAEQgEADgFAAQgGAAgEgDg");
	this.shape_57.setTransform(65.1,0.3);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFF00").s().p("AA1BFQgDgEAAgFIgBgMIgBgMIAAgcIAAgzQgIABgJAAIgqgBIABARIAAARQAAAogFAPQgIAagaAAQgKAAgHgEQgJgFAAgJQAAgFADgEQADgDAFAAIAIACIAHACQAKAAADgOQABgIAAgUIgBgeIgBgfQAAgGAEgDQAEgEAGAAIAJABIAJAAIAkABIAOgCIAPgCQAPAAAAANIAAAiIgBAhIABAbIAAANIABAMQAAAFgDAEQgEAEgGAAQgGAAgEgEg");
	this.shape_58.setTransform(47.3,0.1);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFF00").s().p("AglA6QgTgSAAgcQAAgZASgdQAUgfAXgBQANABAQAFQAUAJABALQAAAFgEAEQgDAEgFAAQgEAAgDgDIgFgEQgIgGgSgBQgLAAgOAZQgMAWAAAOQAAASAMAKQALAJAPAAQAIABAJgFIAQgIQAEgCACAAQAFAAADADQAEAEAAAFQAAALgUAIQgTAJgMgBQgZAAgSgQg");
	this.shape_59.setTransform(32.4,0.3);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFF00").s().p("AgsA5QgVgRAAgdQAAghARgXQASgaAeAAQAVAAAOAIQARAIAAAUQAAANgPALQgHAEgVAIIgxAZQAHALAMAGQALAFAMAAQAKAAAMgDQAQgFAEgHQAFgHAFAAQAFAAADADQAEAEAAAEQAAAQgYAKQgUAJgUAAQgcAAgSgPgAgagiQgLAMgFAXIApgRQAWgMAKgIQgMgLgTAAQgPAAgLANg");
	this.shape_60.setTransform(18,0.3);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFF00").s().p("AAGgdIATgCIgmA9IgMACg");
	this.shape_61.setTransform(-2,5.5);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFF00").s().p("AAqBDQgGgFgDgEQgNAGgKAEQgKADgEAAQgfAAgPgRQgMgRAAghQgBgfAWgWQAXgYAcAAQAMAAAPAHQARAHABALQgBADgCADQgBAFgBALIgBAcQAAAQACALIAIAWIAEAIIABACQAAAGgFADQgDAEgFAAQgDgBgGgGgAgWggQgOAQAAAUQgBAXAIALQAIAKAPABQALAAAJgGQAFgCAJgIQgEghgBgSIABgMIACgOIgIgEIgGgBQgTAAgPARg");
	this.shape_62.setTransform(-12.3,0.4);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFF00").s().p("AhKBEIAAgPIAAgPQABgHAEgDQAEgEAHABQAOgTAEgXQADgRAAgeQABgMAFgFQAGgFAMAAIAMAAIANABIAPgBIAOgBQAKAAADAJQACAFAAANIAAASIgBASIAAAZIABAbQATAAAAANIAAAQIAAARQAAAFgEAEQgDAEgHAAQgNAAAAgWIAAgHIAAgFIhIAAIgMABIgLAAIAAAKIAAAKQAAAGgEAEQgDAEgHAAQgNAAAAgUgAgfAbIAHgBIA1AAIAAgaIAAgYIAAgSIABgRIgoAAQAAAwgVAmg");
	this.shape_63.setTransform(-27.6,1.6);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFF00").s().p("AgIA9QgVgRAAgcIAAgCIgFAAQgNAAgMABIgaAFIgBAtQAAAGgEADQgEADgEAAQgMgBAAgLQAAgZACgbIAEgzIABgNIABgOQAAgMAMAAQAMAAAAAMIgBAPIgBAOIgDAhQAlgFAMgBIAJAAQAIgbARgRQATgUAbAAQBBAAAAA+QAAAfgSAbQgVAfgjAAQgcAAgRgRgAAKgaQgMAUAAAWQAAARAKAKQAMAJARAAQAVAAAOgUQANgUAAgXQAAgUgJgIQgJgIgVAAQgVAAgPAVg");
	this.shape_64.setTransform(-47.9,-0.1);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFF00").s().p("AglA6QgTgSAAgcQAAgZASgdQAUgfAXgBQANABAQAFQAVAJgBALQAAAFgDAEQgDAEgFAAQgEAAgDgDIgGgEQgHgGgSgBQgMAAgNAZQgMAWAAAOQAAASAMAKQALAJAQAAQAHABAKgFIAPgIQAEgCACAAQAFAAADADQAEAEAAAFQAAALgVAIQgRAJgMgBQgZAAgTgQg");
	this.shape_65.setTransform(-67,0.3);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FFFF00").s().p("AAtBqQgDgFAAgFIAAgaIABgZQAAgRgCgPIgYAhQgOATgMALIgbAZQgHAHgHABQgGgBgFgDQgEgDAAgGIgChPIgBgoQAAgNANAAQAMAAABAMIABAZIACBCQAUgSAUgbIAlguQAIgLAJAAQAFAAAEADQAEAEAAAGIABAqIAAAtIAAAQIgBAPQAAAFgEAFQgEADgFAAQgGAAgEgDgAgkhDQgOgMAAgTQAAgKAKAAQAKAAAAAKQAAAKAJAIQAIAGALAAQAlAAAFgVQADgIAHAAQAEAAADACQADAEAAADIAAACQgCAVgWAKQgRAIgVAAQgTAAgPgOg");
	this.shape_66.setTransform(42,-47.4);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FFFF00").s().p("AAqBDQgGgFgDgFQgNAIgJADQgKADgFABQgfAAgOgSQgNgQgBgjQAAgdAXgYQAVgWAeAAQALAAAOAFQATAIgBAKQAAAEgCADQgBAFgBAMIgBAbQgBAQADAKIAIAYIADAHIABACQAAAGgEADQgDADgFAAQgDABgGgHgAgVggQgPARgBATQABAWAHALQAIALAQAAQAKAAAJgEQAFgDAIgHQgEgiAAgRIABgNIACgOIgIgEIgGgBQgSAAgPARg");
	this.shape_67.setTransform(26.9,-43.7);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#FFFF00").s().p("AgyBEQgEgDAAgFIABgUIAAgTIgBgkIAAgnQgBgRAOAAQAGAAAEAEQADADABAGIABAnIAJAAQARgBAFgOIAFgNQALgVAPAAQAEAAAGACQAGADAAAFQABAKgJAAQgIABgIARIgGAOQgFAHgEAFQANAHAPAWQAOAWAAALQAAAFgDAEQgFAEgFgBQgJAAgEgJQgEgJgQgXQgOgYgFAAIgQAAIAAAQIAAAQIgBAYQgCALgLAAQgFAAgFgEg");
	this.shape_68.setTransform(13.6,-44.1);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#FFFF00").s().p("AAqBDQgGgFgDgFQgNAIgKADQgKADgEABQgfAAgPgSQgNgQABgjQAAgdAVgYQAXgWAcAAQAMAAAOAFQASAIAAAKQAAAEgCADQgCAFAAAMIgBAbQAAAQACAKIAJAYIADAHIAAACQAAAGgDADQgEADgFAAQgCABgHgHgAgWggQgOARAAATQgBAWAIALQAIALAPAAQALAAAJgEQAFgDAJgHQgEgiAAgRIAAgNIACgOIgIgEIgGgBQgTAAgPARg");
	this.shape_69.setTransform(-0.5,-43.7);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#FFFF00").s().p("AA/A2IgEgQQgGgQgJgsIgWAzIgHASQgEAKgEAHQgFAGgHABQgHgBgEgFIgIgUQgLgfgJgjIgDAPIgPAtQgBAKgFAQQgDAIgIAAQgNAAAAgLQAAgPAIgXIANgjIAGgdQAFgUAGgGQAFgGAHABQAIAAADAGQAFAJAFAZQAGAdAMAgQAPghAMglIAGgVQAFgMALAAQANAAAFAaIACALQAGAnALAdIAKAgQAAAEgEAEQgEACgFAAQgMAAgFgUg");
	this.shape_70.setTransform(-17.7,-43.9);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#FFFF00").s().p("AgNBaIABgeIABgdIAAgfIgKAAQgKAAgZAoQgXAkgGAQQgDALgJAAQgGgBgEgDQgEgEAAgFQAAgTAZglQAYgkARgIQgRgKgKgaQgNgfgOAAQgHAAAAgLQAAgEAGgDQAGgDAFAAQAWAAANAgIAFAPQAEAMAHAFQAKAIAQAAIgCg3QAAgVAOAAQADAAAEAEQAEAEAAAFIABBAQAQAAAKgHQAHgHAEgLIAGgQQAOggAVAAQAFAAAGADQAHACAAAFQAAALgHAAQgPAAgMAfQgLAagRAKQARAIAYAkQAZAlAAATQAAAFgEAEQgEADgGABQgJAAgDgLQgGgQgWgkQgagogKAAIgJAAIgBAbIAAAcQAAAggBAEQgCAMgJAAQgNAAAAgNg");
	this.shape_71.setTransform(-39.5,-47.4);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#FFFF00").s().p("AtCRWMAAAgiqIaFAAMAAAAiqg");
	this.shape_72.setTransform(0,42.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36}]},1).to({state:[{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36}]},1).to({state:[{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-83.5,-68.5,167,222);


// stage content:
(lib.Безымянный2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_118 = function() {
		/* Остановить на этом кадре
		Если вставить этот код в кадр, то остановит/приостановит воспроизведение на нем.
		Также может использоваться для остановки/приостановки воспроизведения фрагментов ролика.
		*/
		
		this.stop();
		
		/* Нажмите для перехода к веб-странице
		При нажатии на указанный экземпляр символа производится загрузка веб-страницы в новом окне обозревателя.
		
		Инструкции:
		1. Замените http://www.adobe.com на адрес желаемой веб-страницы.
		   Не удаляйте кавычки ("").
		*/
		
		this.addEventListener("click", fl_ClickToGoToWebPage_3);
		
		function fl_ClickToGoToWebPage_3() {
			window.open("https://www.youtube.com/watch?v=FvgSBriElOs");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(118).call(this.frame_118).wait(1));

	// Слой 7
	this.instance = new lib.Символ1();
	this.instance.setTransform(252.2,352.4);
	this.instance.alpha = 0;
	this.instance._off = true;
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.Символ1(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(86).to({_off:false},0).to({y:338.8,alpha:1},6).wait(27));

	// Слой 5
	this.instance_1 = new lib.text3();
	this.instance_1.setTransform(244.4,147.8);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(80).to({_off:false},0).to({x:226.8,alpha:1},6).wait(33));

	// Слой 4
	this.instance_2 = new lib.heart();
	this.instance_2.setTransform(223.9,238.4);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(40).to({_off:false},0).to({alpha:1},20).to({scaleX:51.75,scaleY:51.75},20).wait(39));

	// Слой 3
	this.instance_3 = new lib.text2();
	this.instance_3.setTransform(255,393.6);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(15).to({_off:false},0).to({alpha:1},15).to({_off:true},33).wait(56));

	// Слой 2
	this.instance_4 = new lib.text1();
	this.instance_4.setTransform(259,94.8);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({alpha:1},15).to({_off:true},43).wait(61));

	// Слой 1
	this.instance_5 = new lib.bg();
	this.instance_5.setTransform(250.5,250);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(40).to({_off:false},0).to({alpha:1},10).to({_off:true},13).wait(56));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(321,273.6,376,142.5);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;